### ISSUE TITLE
Proposal3

### ISSUE THREAD

**Issue by jardleex** [mrlesmithjr/ansible-consul#42]
Hello @mrlesmithjr

during the latest work on the role I stumbled upon some things I'd like to create some PR's.

- [ ] Remove standalone setup. Right now it's empty and the comments say that it was intended for later. As there is even offical [Docker container](https://hub.docker.com/_/Consul/) and many guides telling the user how to start playing with a standalone Consul instance, it might be time to remove the standalone task from here.
- [ ] Move `cluster.yml` into `config.yml` once/if #40 gets merged. The first one only handles the encryption key which is part of the configuration.
- [x] Get rid of a deprecation warning with sleep on systemd units (running on Ubuntu 16 here) > #55 .
- [ ] Change default of `consul_enable_dnsmasq` to *false* as it may break some installations (which it did on our side).
- [x] Retire `consul_wan_group` and allow wan joining. > #56 .
- [ ] Remove commented items on directory creation task in `config.yml`.
- [ ] Convert double quotes to single ticks in playbooks where no variable is placed.
- [ ] Improve role documentation. Right now it feels a bit strange to put the very same text block into `defaults/main.yml` and `README.md`. Do you have other roles with another documentation attempt you'd like to have here too?

Is there something you wanted to touch on this role as well some when? May it's no big deal and I may provide a PR for it.

One thing I can't (I hope thats true) with a PR are tags for the role. The changes applied in the last month might have broken some ones setup. In order to prevent that offering tags would be a nice way. Right now even at my job we use the commit hash of this repository to pin a specific version to avoid unexpected behaviors.

Let me know what you think.

As always,
Best regards

Jard

**Comment by jardleex** [comment]
I'm closing this as the points may become obsoloete these days. I ain't have the resources to check and update the issue.
